name:                free-matched-parsing
version:             0.1.0.0
github:              "michaeljklein/free-matched-parsing"
license:             BSD3
author:              "Michael J. Klein"
maintainer:          "lambdamichael@gmail.com"
copyright:           "2018 Michael J. Klein"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/michaeljklein/free-matched-parsing#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- comonad
- constraints
- foldl
- free
- generics-sop
- ghc-typelits-natnormalise
- mtl
- pointed
- primitive
- profunctors
- reflection
- transformers
- vector

library:
  source-dirs: src

executables:
  free-matched-parsing-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - free-matched-parsing

tests:
  free-matched-parsing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - free-matched-parsing
